permalink: /:title/
root_dir: "http://ovdinfo.github.com/reports"
baseurl: "http://reports.ovdinfo.org"
oauth_client_id: caf55c20366465a1332d
gatekeeper_url: http://poole-oauth-staging.herokuapp.com
highlighter: rouge
markdown: kramdown